  version: '3'
  services:
    express-typescript:
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      env_file: .env
      volumes:
        - .:/usr/src/app
      container_name: usersApi
      expose:
        - '${port}'
      ports:
        - '${port}:${port}'
